# Action.

uint32 action

uint32 GET_VERTEX_DESCRIPTOR=0
uint32 GET_EDGES_DESCRIPTORS=1
uint32 LOCALIZE_IN_VERTEX=2
uint32 LOCALIZE_EDGE=3
uint32 GET_SIMILARITY=4
uint32 INTERRUPT=5
uint32 CONTINUE=6

LamaDescriptorIdentifier descriptor
---
# Result.

uint32 state
uint32 DONE=0
uint32 NOT_SUPPORTED=1

LamaDescriptorIdentifier[] descriptors
# Data output, dependent on action.
int32[] idata
float32[] fdata
 
duration completion_time
---
# Feedback.

# Completion is -1 if unknown, 0 if just started, 1 if finised
float32 completion
duration time_elapsed
